# Deploy

name: dashboard-deploy

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@master
            - name: Check Tag
              id: check-tag
              run: |
                  if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
                      echo ::set-output name=match::true
                  fi
            - name: Run builder script over SSH
              if: steps.check-tag.outputs.match == 'true'
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEUS_HOST }}
                  port: 22
                  username: ${{ secrets.DEUS_USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      cd ~/builder/dashboard
                      git pull
                      yarn install
                      yarn build
    deploy:
        needs: ['build']
        runs-on: ubuntu-latest
        steps:
            - name: Run deployment script over SSH
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.DEUS_HOST }}
                  port: 22
                  username: ${{ secrets.DEUS_USERNAME }}
                  key: ${{ secrets.KEY }}
                  script: |
                      rm -rf ~/deus/web/dashboard
                      mkdir ~/deus/web/dashboard
                      cp -r ~/builder/dashboard/dist ~/deus/web/dashboard
